### ISSUE TITLE
可否增加功能，一次插入同一引用的多个形态【第#页码 页 #标题编号 #标题文字】

### ISSUE THREAD

**Issue by Robert-Wang-08** [shishouyuan/HandyRefVBA#3]
office365使用成功，感谢
目前默认黏贴的是原 标题文字， 且具备同样的格式（如 标题级别）
可否增加一个选项  一次插入第#页码 页 #标题编号 #标题文字 ？

**Comment by zlyc8** [comment]
建议为其他引用类型也添加快捷键，目前只能通过点击下拉列表再选择引用类型，比较繁琐

**Comment by shishouyuan** [comment]
@Robert-Wang-08 你好，其他形式的引用功能在最新版加入了，可以试试

**Comment by shishouyuan** [comment]
@yichaocp 你好，因为这个插件没有提供给用户的设置选项，我担心弄太多快捷键会和别人设置的快捷键冲突，就准备先不加太多快捷键哈。

**Comment by atomcow** [comment]
@Robert-Wang-08 把其他引用类型加载到“快速访问工具栏”，然后利用快速访问工具栏的快捷键。ALT+4 ,ALT+5等。曲线救国。哈哈

**Comment by shishouyuan** [comment]
@atomcow 优秀哎
